apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}-backend
  labels:
    app: {{ include "todo.fullname" . }}-backend
spec:
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "todo.fullname" . }}-backend
  type: ClusterIP
